final sampleData = <String>[
  'Adi Shamir',
  'Alan Kay',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Andrew Yao',
  'Barbara Liskov',
  'Kristen Nygaard',
  'Leonard Adleman',
  'Vinton G. Cerf',
  'Leslie Lamport',
  'Ole-Johan Dahl',
  'Peter Naur',
  'Robert E. Kahn',
  'Ronald L. Rivest',
];
